#!/bin/bash
clear
echo -e "\033[32;1m====================================="
figlet Hh1
echo -e "\033[0m"
echo -e "\033[32mHost Header Injection by \033[32;1mpaktiko1986\033[0m"
echo -e "\033[32;1m====================================="
echo "Host Header Injection - Detector"
echo "====================================="
echo "[+] Total target(s): " $(cat $2 | wc -l)
echo "[+] Payloads: "
echo "    >> Host: google.com"
echo "    >> X-Forwarded-Host: google.com"
echo "    >> Content-Length: 0"
echo -e "=====================================\033[0m"
if [[ ! $1 == "--d" && $2 == "" ]]; then
	echo "--d: fill with URL target (single domain or subdomain list in file)"
	echo "Example: --d google.com | --d subdomain.txt"
else
	for url in $(cat $2); do curl -skLI -H "Host: google.com" -H "X-Forwarded-Host: google.com" -H "Content-Length:0" -A "User-Agent: SKH86" $url | grep -q "domain=.google.com" && echo -e "\033[31m[-] $url is VULN\033[0m" || echo -e "\033[32m[+] $url is WELL\033[0m";  done
fi
